### ISSUE TITLE
[Discussion] Complex Animation Feature

### ISSUE THREAD

**Issue by ktabata** [suika2engine/suika2#101]
* Idea 1: Create Animation definition file such as GUI definition file
* Idea 2: Use Lua plugin to realize the animation

**Comment by KyouBrayden** [comment]
I like the idea of being able to define them.

Regarding the definition file, would something like the following be a starting point (I have no idea on the complexity of implementation, so this is, of course, just 'thinking out loud'):

```
###
### Animation Definition for Move-Left
###

# Initial Position (Acts as keyframe 1)
initial-position {
    x: <x Position>
    y: <y Position>
    opacity: <Initial Opacity>
}

# End Position (Acts as keyframe 2)
end-position {
    x: <x Position>
    y: <y Position>
    opacity: <End Opacity>
}

# Movement
movement {
    speed: <Speed>
}

# Overlay (Optional)
overlay {
    overlay-file: <Overlay File>
}
```

`initial-position` is the starting position of the animation, could be taken from the image's current pos?
`end-position` where the animation ends, the image will be here at animation end.
`opacity` is the transparency of the image. Optional, reads opacity from the image if not provided in-file.
`speed` is the speed at which the animation moves, could be between `0 – 1`?
`overlay` just an idea, a secondary image superimposed, a image file could look like an effect or something like that.

I'm sure there would be other things as well.

**Comment by ktabata** [comment]
Thank you for the idea.
In this idea, we can move a sprite on a layer.
Let's extend this a bit to allow the definition of repeated animations and simultaneous animations.
Then perhaps we will need the "animation slots."

* All sprites on the screen are defined as layers.
* An animation slot defines the movement of a single layer.
* Multiple animation slots can be executed simultaneously.

Your idea has inspired me to envision such a design.

**Comment by KyouBrayden** [comment]
Oh, I completely forgot about some of the extras you mentioned there, thank you!

As a follow-up, I can't recall whether or not Suika supports `APNG`? If so, do you think something like the `overlay` animation argument could support `APNG` for a more visually pleasing experience? If I recall correctly, regular `PNG` decoding can read the first 'image' of `APNG` streams? I'm not sure if `APNG`'s licensing is similar to `PNG`. – Just an extra idea, please let me know your thoughts!

**Comment by ktabata** [comment]
Of course it is possible to use APNG. However, there is a concern that the load on the computer will be higher.
How about implementing the animation first, and then consider the APNG after that?
We will be able to handle APNGs only after the animation is implemented, and we can experiment with the system load at that time.

**Comment by KyouBrayden** [comment]
True, thank you for the reminder!

**Comment by RaZZlom** [comment]
Idea from Discord about credits animation:

"Text file with credits. At the end of game use something like `@credits credits.txt` and it scroll text on screen with option to skip it with keypress."

https://discord.com/channels/986623112617541677/986637208335314954/1053211031209525318
