### ISSUE TITLE
[Discussion] 64-bit Intel Windows binary

### ISSUE THREAD

**Issue by ktabata** [suika2engine/suika2#102]
Does anyone need a 64-bit Intel Windows binary?
We already have it, but we haven't been including it in the releases.
The reason we use 32-bit binary is that it is perfectly emulated in the ARM64 environment such as Surface Pro X.
Please tell me if we need to separate binaries for x86, x86_64, and ARM64.

**Comment by innocentvoice** [comment]
Oh i think i don't need it. But thanks for asking.

**Comment by ktabata** [comment]
Thank you.
So let's distribute only 32-bit exe until Windows 10 support ends.
