### ISSUE TITLE
[Discussion] v2.12 goals and schedule

### ISSUE THREAD

**Issue by ktabata** [suika2engine/suika2#103]
* Please let us know as many changes as possible that need to be made.
* I will be away from November 21 through November 25, so I hope to release as much as possible by November 20.

**Comment by KyouBrayden** [comment]
This is just what I could think up now, obviously some of these will not be possible in a short amount of time or at all, but I'll include them on the off chance.

* Reviewed script (We can discuss this together when you have a script for Midori's ENCV)

* Menubar additions (I'm not sure how possible these are, so please ignore any that can't be done):
  * 'Story' Menu:
    * Return to Title Screen
    * Enable / Disable Skip Mode
    * Enable / Disable Auto Mode
  * 'View' Menu:
    * Enable / Disable Click Animation
    * Select Font / a list of available fonts
    * Use Regular Cursor (see below)

* Custom cursor (Not sure if this is possible cross-platform?)
* Controller (gamepad) support
* Message box in-script text alignment (left, centre, right – respects margins)
* Pure-text switches (I doubt this will be addable with the current implementation, but thought I'd be annoying again!)

Will update if anything else pops up.

**Comment by ktabata** [comment]
Thank you so much. Could you create the issues separately and put refers to this issue on them?
Let's discuss!
