### ISSUE TITLE
[Discussion] Plugin Language

### ISSUE THREAD

**Issue by ktabata** [suika2engine/suika2#104]
* Lua
* Tiny JavaScript Interpreter
* Tiny JavaVM
* Original Script Interpreter

**Comment by giovifav** [comment]
i vote for lua, it's fast (specially luaJIT), it's easy to embed, it's very easy to use for begginers and non programmer.

**Comment by ishani-rgb** [comment]
Lua is kost often used for a task like this, and its simpler to learn and write compared to Java and Javascript. My vote goes to it too.

**Comment by RaZZlom** [comment]
"Original Script Interpreter" - this is current Suika2Script?

Maybe Lua best variant, but how it impact on suika performance and portability?

**Comment by ktabata** [comment]
> "Original Script Interpreter" - this is current Suika2Script?

No, I mean we can design and implement a new language for our plug-ins.

**Comment by RaZZlom** [comment]
> we can design and implement a new language for our plug-ins.

This is very hard and long work. I don't think this is worth it.

And what kind of plugins you want to create with e.g. lua?

**Comment by ktabata** [comment]
Thank you for the comment.
I didn't mention but I'm a language / compiler / virtual machine expert.
It takes less than three days to create a new language.
If we need a domain-specific, easy-to-use language, then I'll create it.

**Comment by ktabata** [comment]
We introduced WMS (Watermelon Script) for this purpose.
It’s easier for non-programmers to write.
We’ll be adding the Suika2 Engine API for this programming environment.
