### ISSUE TITLE
[Discussion] Menubar Additions

### ISSUE THREAD

**Issue by ghost** [suika2engine/suika2#107]
Please comment with any comments, additions, or revisions to the menubar you believe should be discussed further.
See [[Discussion] v2.11.8 goals and schedule](https://github.com/suika2engine/suika2/issues/103)

Some additions:
* 'Story' Menu:
  * Return to Title Screen
  * Enable / Disable Skip Mode
  * Enable / Disable Auto Mode
* 'View' Menu:
  * Enable / Disable Click Animation
  * Select Font / a list of available fonts
  * Use Regular Cursor (see below)

**Comment by ktabata** [comment]
So your requirement is that you do not want to display image-based system menu bar or config screen?

**Comment by KyouBrayden** [comment]
More-so to append some other functions to the menubar for easy access if it is displayed. Although, I should have checked and noticed that it is a lot of the configuration screen. You can probably close this issue in that case.

**Comment by ktabata** [comment]
No problem. I assume you are hiding the system menu, so these menu items are a must.
By the way, you can add menus as text window decorations. If this is closer to your image, you can use this.

**Comment by a-rabin** [comment]
Is it also possible to make this feature user-definable?

**Comment by ktabata** [comment]
> Is it also possible to make this feature user-definable, as in users can define own window menubars?

Do you have an example menu item?

This is a policy of not being unnecessarily flexible; Suika2 is not a programming language or environment, so if a feature is not actually needed, it will not be implemented. The same reason we don't have plug-ins.

**Comment by a-rabin** [comment]
> Do you have an example menu item?
If it becomes available in future, a section for advanced menus, as well as dynamic language changing.
Another suggestion would be for VN controls not commonly found with the current build, such as One Line Back.
Also I have merely put it out as a question. Thank you for answering!

**Comment by ktabata** [comment]
Thank you for reply. 

Dynamic language changing and One line back should be implemented as basic features that Suika2 natively supports. Menu is not related.

Suika2 is not like KiriKiri. We don't implement any feature by user scripting because it's not a versatile scripting engine. This is not a limitation but our clean design policy. 

We're going to use Lua but it's only for animation. We will not provide API for the engine extensions. 

Please consider create issues for these functionalities separately.
