### ISSUE TITLE
[Discussion] Controller (Gamepad) Support

### ISSUE THREAD

**Issue by ghost** [suika2engine/suika2#108]
Introduce controller (gamepad) support as a valid input method.
See [[Discussion] v2.11.8 goals and schedule](https://github.com/suika2engine/suika2/issues/103)

**Comment by ktabata** [comment]
To be able to control everything with a gamepad we must first allow keyboard control without a mouse.

**Comment by RaZZlom** [comment]
> Introduce controller (gamepad) support as a valid input method.

> To be able to control everything with a gamepad we must first allow keyboard control without a mouse.

Yes, please! This is first step to conqueror consoles!

I have Logitech, Playstation 3 and two Playstation 4 gamepads to test.

**Comment by KyouBrayden** [comment]
I can offer XBOX SeriesS/360 controller tests when the time comes for double-checking.
