### ISSUE TITLE
[Discussion] Alignment, Colour, and Size 'Editing'

### ISSUE THREAD

**Issue by ghost** [suika2engine/suika2#109]
More advanced text manipulation, mainly message box in-script text alignment (left, centre, right) that respects message box margins.
See [[Discussion] v2.11.8 goals and schedule](https://github.com/suika2engine/suika2/issues/103)

Perhaps a specifier of some kind or a command that indicates specialised formatting.

**Comment by ktabata** [comment]
That will be good improvement.
Shouldn't we also consider the ability to change the size and color of the text at the same time?

**Comment by KyouBrayden** [comment]
That's a good point. I'll rename to 'Alignment, Colour, and Size'.
