### ISSUE TITLE
[Discussion] Pure Text Switches

### ISSUE THREAD

**Issue by ghost** [suika2engine/suika2#111]
Switches (`@choose`, `@select`, `@switch`, `@news`) can be displayed as pure text rather than an image / image with a transparent background.

Pure text refers to text in the way it is displayed for messages.
Particularly useful in NVL style stories.

See [[Discussion] v2.11.8 goals and schedule](https://github.com/suika2engine/suika2/issues/103)

**Comment by ktabata** [comment]
May I ask a little more about this? Where will the text be output?

**Comment by KyouBrayden** [comment]
I feel the most appropriate place would be within the message box, in a similar way to a 'new message'. Appended to any previous messages as a new message block.

```
Previous messages...

Question goes here.
Option 1
Option 2
Option 3
```

**Comment by ktabata** [comment]
Unfortunately, the message box is designed specifically for output, so it cannot directly support it.
It is possible to approximate it by adding a config to display choose options at the current text display position.

**Comment by KyouBrayden** [comment]
That might be an interesting method to test in the future?

**Comment by ktabata** [comment]
Alternatively, the following combinations are possible in the future.

Messages.

\q1Option1
\q2Option2
\q3Option3

@choose \q1 \q2 \q3

**Comment by KyouBrayden** [comment]
That sounds like a good alternative solution to try out at some point.

**Comment by RaZZlom** [comment]
I think changing all the buttons from images to text would be a better idea. It's easier to translate text than to edit a lot of images.

**Comment by KyouBrayden** [comment]
> I think changing all the buttons from images to text would be a better idea. It's easier to translate text than to edit a lot of images.

Message-switches are sufficient, no? Image-maps as menu's are pretty standard, and translated use-case isn't all that high.

Either way, if the above system mentioned by @ktabata is implemented in the future, it could allow the building of menus through an NVL screen (they're just loops/jumps at the end of the day) – win/win. Even better if changeable message-box are implemented later on down the line.

**Comment by RaZZlom** [comment]
> Switches (`@choose`, `@select`, `@switch`, `@news`) can be displayed as pure text rather than an image / image with a transparent background.
> Pure text refers to text in the way it is displayed for messages. Particularly useful in NVL style stories.

It can be useful for this use case.

> I think changing all the buttons from images to text would be a better idea. It's easier to translate text than to edit a lot of images.

Here i say that now all in game buttons is just image. It will be better if we have buttons with image background and text. This is what i mean.
