### ISSUE TITLE
[Bug] [Android] Need to press twice on buttons

### ISSUE THREAD

**Issue by innocentvoice** [suika2engine/suika2#112]
This bug happened on Android. I need to press twice on every button of the GUI to make it works. However, it does not affect the text dialog and the choices.

Device: Xiaomi Mi 11T Pro
OS: Android 12
Suika2 Version: 2.9.11

**Comment by ktabata** [comment]
Thank you for the report.
Version 2.9.11 is very old. Is it correct version?

**Comment by innocentvoice** [comment]
Yes! 
![IMG_20221112_202915](https://user-images.githubusercontent.com/81401361/201476337-aa1e1fd9-fbcc-4abf-8d6f-f578dd42c81c.jpg)

**Comment by RaZZlom** [comment]
Can confirm this bug with last build (https://github.com/suika2engine/suika2/actions/runs/3507811053).

First tap working like hover, second tap like click.

Device: OnePlus 8T
OS: Android 12
Suika2 Version: 2.9.11

**Comment by ktabata** [comment]
Thank you for the report!
I can't use my computer now and will fix this bug over the weekend.

**Comment by ktabata** [comment]
I thought it would be a straightforward bug, but it wasn't. It was a race condition!
I found that the rendering and the event handling are done on different threads.
So I added synchronizations to resolve the bug.
I'll push the code later.
