### ISSUE TITLE
[Discussion] Additional setting for slots

### ISSUE THREAD

**Issue by Max-Morgan** [suika2engine/suika2#114]
Question for everyone, do you want see additional settings for slots?

We had an idea to create more settings for: screenshots and text (time, message, scene name and page number)

For example: You can place a screenshot and text anywhere in the slot! But a question arose, do you need a different size for each text setting?

We mean:
```
slot.time.size=30
slot.page.size=30
slot.message.size=30
slot.scene.size=30
```

Or just:
`slot.text.size=30`

How would you like it?

**Comment by KyouBrayden** [comment]
Slots – as in save/load or CG galleries?

**Comment by Max-Morgan** [comment]
save/load
![64354354](https://user-images.githubusercontent.com/116950820/201499831-4e623c67-0b0a-408b-8c09-6f063036fbc5.jpg)

**Comment by KyouBrayden** [comment]
I like the idea of being able to adjust those sizes.
It might also be nice to have the ability to toggle them (each individually) off completely (unless that's already in there, I may have missed it!)
