### ISSUE TITLE
[DISCUSSION] Date Image

### ISSUE THREAD

**Issue by ghost** [suika2engine/suika2#127]
A togglable image similar to that of the face-sprite.

Like other engines it could, by default, be located in the top left corner of the stage.

**Show:**
```
@date filename.ext 1.5
```
**Hide:**
```
@date none 1.5
```

Where `1.5` is an optional fade-in/out time.

**Possible config.txt entry for a user-togglable menu option:**
```
# Date Image (0:show, 1:hide)
date.show=0

# Position to show the date image
date.x=x_pos
date.y=y_pos
```

I can share example images from games via Discord if anyone is interested.
I know it adds another image to deal with, so please let me know what you think.

**Comment by ktabata** [comment]
How about adding ”date" position to `@ch` command?
Wouldn't that be intuitive?

**Comment by KyouBrayden** [comment]
Would that retain the four character positions already in use?
If so, that would make more sense, I didn't think of that.
