### ISSUE TITLE
[FEATURE] Random Image

### ISSUE THREAD

**Issue by ghost** [suika2engine/suika2#132]
An implementation to allow for the display of a random image.

```
@bg [list of background images] random
```
To stay with arguments, which might be more intuitive.

Or:

```
@random [list of background images]
```

Usage case: Mini-games. Combined with the current system of random number generation, this could greatly improve the depth of 'out-of-the-box' mini-games.

I'd be interested to know if you think it is worth it, or any alternative ways it could be implemented.

**Comment by RaZZlom** [comment]
When change image? After new line of text? After some time? After clicking on `@choose` element?

**Comment by KyouBrayden** [comment]
> When change image? After new line of text? After some time? After clicking on `@choose` element?

All of the above could be achieved if either implementation I provided was used.
They are all independent from each other, so it wouldn't matter as developer's would work that out within the layout of their scripts.

**Comment by RaZZlom** [comment]
This variant better `@bg [list of background images] random` than `@random [list of background images]` because just `@random` is too common, e.g. we need something like `@randombg`, `@randomcg` etc.
