### ISSUE TITLE
[BUG] duplicate label using `using` target the wrong one

### ISSUE THREAD

**Issue by minirop** [suika2engine/suika2#218]
My files are as follow:

outer.txt
```
@if $0 < 3 END
some irrelevant code
:END

using inner.txt
```

inner.txt
```
@set $1 += 1
@if $1 > 3 END
@set $1 = 0
@set $2 += 1
:END
```

Executing this code will increment $2 and leave $1 to 0 since the @if will jump to line 3 of outer.txt.

Should suika assert when detecting duplicate?
Should we have a way to namespace "automatically" labels like the dot prefix in assembly? (e.g. `:.END` would become `<filename>_END`)

**Comment by ktabata** [comment]
Sorry, I realized too late that you wrote this issue.
Yes, we don't have a label namespace.

There are two problems:
1. We should use prefixes in `inner.txt`
2. We need defence for `using` keyword.

We can avoid 2 by a guard by `@goto`:
```
@goto MACRO_END
using inner.txt
:MACRO_END
```

As for 1, fundamentally, we need to structured `if` as you have presented on Discord.

**Comment by ktabata** [comment]
Implemented structured syntaxes in https://github.com/ktabata/suika2/commit/c060e0c961e70d4de0bf569f6f6ee22e890357a9
