### ISSUE TITLE
feature suggestion: multiple text box types

### ISSUE THREAD

**Issue by sherlach** [suika2engine/suika2#23]
Hi TABATA!

I notice that you can customise character message colours in config.txt. Some games like to have different themed name and message boxes too for different characters/narration, or the ability to put character sprites next to the character label when their dialogue appears.

I'm not sure what your prioritisation for upcoming features is, but I think this could be very useful.

Also, I see your english demo - I'm making some edits now. My current plan is to focus on idiomatic English expression more than preserving the original, is that ok?

**Comment by ktabata** [comment]
Hi Loch,

I'm considering multiple themes of the text box and ability to put character sprites on the text box.
Do you want different themes of the text box per characters? Or just want to change it occasionally?
You can change the demo semantically if it becomes more natural to English speaking people.

Thanks!

**Comment by sherlach** [comment]
I think different text box designs to suit the personality of the character is the most likely usage for this feature. However, in games with multiple sections/routes, maybe the developer will want to have a different design for different routes?

I might return to the demo later on, there were some lines which were passable but a little bit clunky... I can fix them later on.

Did you see the message about Save Menu and line wrapping? I attached a comment to the pull request

**Comment by ktabata** [comment]
If we use different text boxes for each character, we have to allocate more memory for the images of the text boxes. It will slow down the speed of Suika2. We should consider the requirements of real games and implement it in a careful way.
I saw your message about save/load screen and word wrapping. I've already pushed it to GitHub and will release the binaries. From version 2.8.3, we'll release English version and Japanese version separately. Please wait for a while.
