### ISSUE TITLE
[BUG] packaging not working with subdirectories on linux (and possibly MacOS)

### ISSUE THREAD

**Issue by minirop** [suika2engine/suika2#256]
I compiled and used tools/pack on my project and got an error that it couldn't find `lake/day-1.txt` which is to be expected since the path should have been `txt/lake/day-1.txt`.

Looking into the code, inside the linux version of `get_file_names_recursive`, we have:
```c
snprintf(entry[file_count].name, FILE_NAME_SIZE, "%s/%s", dir, names[i]->d_name);
```
where `dir` equals `lake` and not `txt/lake`. As a test, I replaced `dir` with `newpath` but later the path is cluttered with ./ and it adds the file `././<path>`
so I added "+4" to remove those so the .arc file is generated but then suika tells me it can't find `conf/config.txt`. Even though my added log says it has been added.

**Comment by ktabata** [comment]
Fixed in https://github.com/suika2engine/suika2/commit/f3b8a3ea70a197aff83066a363045f3ef1614a91

**Comment by ktabata** [comment]
Basically `base_dir` is not used in Windows (it's just NULL) and we can remove it for Linux/macOS, but I left it as is this time.
